From: Andrey Somov <py4fun@gmail.com>
To: yaml-core@lists.sourceforge.net
Subject: [ANN] SnakeYAML-1.5: Improve usage of generic collections in JavaBeans

==========================
 Announcing SnakeYAML-1.5
==========================

A new release of SnakeYAML is now available:

    http://code.google.com/p/snakeyaml/

This release delivers better support for usage of generic collections in JavaBeans, 
as well as other minor changes and bug fixes. It is backwards compatible with the 1.4 release.

Changes
========
 * Improve usage of generic collections
 * Performance improvements
 * Add possibility to define a custom Class Loader

The complete list of changes is here: http://snakeyamlrepo.appspot.com/releases/1.5/site/changes-report.html 

Resources
==========

SnakeYAML homepage: http://code.google.com/p/snakeyaml/
SnakeYAML documentation: http://code.google.com/p/snakeyaml/wiki/Documentation

JAR package: http://snakeyamlrepo.appspot.com/repository/org/yaml/snakeyaml/1.5/snakeyaml-1.5.jar
Reports: http://snakeyamlrepo.appspot.com/

SnakeYAML Mercurial repository: http://snakeyaml.googlecode.com/hg/
Submit a bug report: http://code.google.com/p/snakeyaml/issues/entry

YAML homepage: http://yaml.org/
YAML-core mailing list: http://lists.sourceforge.net/lists/listinfo/yaml-core

About SnakeYAML
================

SnakeYAML is a YAML parser and emitter for Java 5.

SnakeYAML features a complete YAML 1.1 parser.
SnakeYAML is applicable for a broad range of tasks from complex
configuration files to object serialization and persistence.

Copyright
==========

SnakeYAML is developed by Andrey Somov <py4fun@gmail.com>

SnakeYAML is released under the Apache License Version 2.0
