From: Andrey Somov <py4fun@gmail.com>
To: yaml-core@lists.sourceforge.net
Subject: [ANN] SnakeYAML: migration to Google Code

===============================
 Announcing SnakeYAML migration
===============================

SnakeYAML project has migrated to Google Code:

   http://code.google.com/p/snakeyaml/


May I ask to update the link to the project on the YAML page ?
(http://www.yaml.org/)



Thanks to Google for providing Mercurial support. Now Google is used
to host the whole project infrastructure:
- project home
- source
- wiki (documentation)
- download
(via AppEngine)
- generated project reports
- Maven 2 repository
- InstantYAML (http://instantyaml.appspot.com/) application

About SnakeYAML
===============
SnakeYAML features a complete YAML 1.1 parser for Java

Copyright
=========

SnakeYAML is developed by Andrey Somov <py4fun@gmail.com>.

SnakeYAML is released under the MIT license.
